# svdeeq-backend/app/services/memory.py
#
# Manages the hybrid memory model from PRD §2.2:
#   - Recent window: last N exchanges included in every prompt
#   - Persistent summary: updated every 5 messages, stored in sessions table
#
# The summary is generated by asking the LLM to compress older context.
# This way context never gets lost even in very long conversations.

from uuid import UUID
from app.core.supabase import get_supabase
from app.core.config import get_settings
from app.models.schemas import ConversationContext
from app.utils.logger import log

settings = get_settings()


async def get_context(lead_id: UUID, lead_name: str) -> ConversationContext:
    """
    Fetches conversation context for a lead in a single Supabase RPC call.
    Returns a ConversationContext ready to be passed to llm.py.
    """
    db = get_supabase()

    result = db.rpc("get_conversation_context", {
        "p_lead_id":      str(lead_id),
        "p_recent_limit": settings.memory_recent_window,
    }).execute()

    data = result.data or {}

    return ConversationContext(
        lead_id=lead_id,
        lead_name=lead_name,
        summary=data.get("summary"),
        recent=data.get("recent", []),
        message_count=data.get("message_count", 0),
    )


async def maybe_update_summary(lead_id: UUID, message_count: int) -> None:
    """
    Called after every AI reply. If the message count has crossed a
    summary interval boundary, generates a new summary and saves it.

    Interval is controlled by MEMORY_SUMMARY_INTERVAL (default: 5).
    """
    if message_count % settings.memory_summary_interval != 0:
        return

    db = get_supabase()

    # Fetch recent messages to summarise
    msgs_result = (
        db.table("messages")
        .select("sender, content, timestamp")
        .eq("lead_id", str(lead_id))
        .in_("sender", ["USER", "AI"])
        .order("timestamp", desc=False)
        .limit(30)  # summarise up to 30 messages of history
        .execute()
    )

    messages = msgs_result.data or []
    if not messages:
        return

    # Build a simple transcript for the LLM to summarise
    transcript = "\n".join(
        f"{m['sender']}: {m['content']}" for m in messages
    )

    # Import here to avoid circular dependency
    from app.services.llm import generate_summary

    summary = await generate_summary(transcript)

    # Save to sessions table
    db.table("sessions").update({
        "conversation_summary":  summary,
        "summary_message_count": message_count,
    }).eq("lead_id", str(lead_id)).execute()

    await log.info(
        "SUMMARY_UPDATED",
        lead_id=lead_id,
        metadata={"message_count": message_count},
    )
